test_data={'image_png_file': WindowsPath('testdata/files/kartinka_dlay_api_klienta.png')}
http_client={'url': HttpUrl('http://localhost:8000/'), 'timeout': 100.0}
allure_results_dir=allure-results
os_info=Windows, 11
python_version=3.14.0 (tags/v3.14.0:ebf955d, Oct  7 2025, 10:15:03) [MSC v.1944 64 bit (AMD64)]